name: CI

on: [push, pull_request]

jobs:
    main:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['12.x', '14.x', '16.x']
                os: [ubuntu-20.04, windows-2022, macOS-11]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: yarn

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test --ci --coverage --maxWorkers=2

            - name: Upload Codecov Coverage
              if: matrix.node == '16.x' && matrix.os == 'ubuntu-20.04'
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

    # fails in windows because it uses crlf
    prettier:
        name: Check prettier on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: yarn

            - name: Prettier(check)
              run: yarn prettier:base --check
