name: CI

on: [push, pull_request]

jobs:
    main:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['18.x']
                os: [ubuntu-20.04]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - uses: pnpm/action-setup@v2

            - name: Install
              run: pnpm i

            - name: Lint
              run: pnpm lint

            - name: Build
              run: pnpm -r build

            - name: Test
              run: pnpm -r run test --ci --coverage --maxWorkers=2

            - name: Upload Codecov Coverage
              if: matrix.node == '18.x' && matrix.os == 'ubuntu-20.04' && startsWith(github.head_ref, 'renovate/') == false
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

    # fails in windows because it uses crlf
    prettier:
        name: Check prettier on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['18.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - uses: pnpm/action-setup@v2

            - name: Install
              run: pnpm i

            - name: Prettier(check)
              run: pnpm prettier:base --check
